<a href="https://colab.research.google.com/github/Kymapo/AMATH581/blob/main/AMATH581HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
def newton_method(f, df, guess, tol = 1e-6):
  xn = float(guess)
  A1 = [xn]
  x_old = xn + 1
  while abs(xn - x_old) > tol:
    x_old = xn
    xn = x_old - f(x_old) / df(x_old)
    A1.append(xn)

  return A1

f = lambda x: x * np.sin(3*x) - np.exp(x)
df = lambda x: np.sin(3*x) + 3 * x * np.cos(3*x) - np.exp(x)
A1 = newton_method(f, df, -1.6)
print(A1)

[-1.6, 3.1979951385210694, 2.4644024441424284, 1.2035359007112925, 0.6502014632644292, -0.1169233418248703, -0.6605234854521386, -0.5219265439062168, -0.5665527428708069, -0.5707465821813341, -0.57078961788788, -0.57078962246829]


In [13]:
def bisection_method(f, boundaries, tol = 1e-6):
  lb = boundaries[0]
  rb = boundaries[1]
  if np.sign(f(lb)) == np.sign(f(rb)):
    return 'Choose different boundaries'
  xn = float((lb + rb) / 2)
  A2 = []
  while abs(f(xn)) > tol:
    xn = float((lb + rb) / 2)
    if np.sign(f(xn)) == np.sign(f(lb)):
      A2.append(xn)
      lb = xn
    else:
      A2.append(xn)
      rb = xn

  return A2

f = lambda x: x * np.sin(3*x) - np.exp(x)
A2 = bisection_method(f, (-0.7, -0.4))
print(A2)

[-0.55, -0.625, -0.5875, -0.5687500000000001, -0.578125, -0.5734375, -0.5710937500000001, -0.5699218750000001, -0.5705078125, -0.57080078125, -0.570654296875, -0.5707275390625, -0.57076416015625, -0.570782470703125, -0.5707916259765625, -0.5707870483398438, -0.5707893371582031]


In [14]:
A3 = [len(A1), len(A2)]
print(A3)

[12, 17]


In [15]:
A = np.array([[1, 2], [-1, 1]])
B = np.array([[2, 0], [0 ,2]])
C = np.array([[2, 0, -3], [0, 0, -1]])
D = np.array([[1, 2], [2, 3], [-1, 0]])
x = np.array([[1], [0]])
y = np.array([[0], [1]])
z = np.array([[1], [2], [-1]])

A4 = A + B
A5 = 3 * x - 4 * y
A6 = A @ x
A7 = B @ (x - y)
A8 = D @ x
A9 = D @ y + z
A10 = A @ B
A11 = B @ C
A12 = C @ D

print(A4)
print(A5)
print(A6)
print(A7)
print(A8)
print(A9)
print(A10)
print(A11)
print(A12)

[[ 3  2]
 [-1  3]]
[[ 3]
 [-4]]
[[ 1]
 [-1]]
[[ 2]
 [-2]]
[[ 1]
 [ 2]
 [-1]]
[[ 3]
 [ 5]
 [-1]]
[[ 2  4]
 [-2  2]]
[[ 4  0 -6]
 [ 0  0 -2]]
[[5 4]
 [1 0]]


In [16]:
np.save('A1.npy', A1)
np.save('A2.npy', A2)
np.save('A3.npy', A3)
np.save('A4.npy', A4)
np.save('A5.npy', A5)
np.save('A6.npy', A6)
np.save('A7.npy', A7)
np.save('A8.npy', A8)
np.save('A9.npy', A9)
np.save('A10.npy', A10)
np.save('A11.npy', A11)
np.save('A12.npy', A12)

In [18]:
#loaded_data = np.load('A1.npy', allow_pickle=True) # Add allow_pickle=True to load the data containing objects
#print(loaded_data)